### ISSUE TITLE
Invalid version (expected 2, but 60) or the data in not in 'javabin' format :ConcurrentUpdateSolrClient

### ISSUE THREAD

**Issue by DivyaYash** [jcustenborder/kafka-connect-solr#12]
[2017-12-08 13:34:48,710] WARN Failed to parse error response from http://<hostname>:8983/solr/<collecname>due to: java.lang.RuntimeException: Invalid version (expected 2, but 60) or the data in not in 'javabin' format (org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient:343)
[2017-12-08 13:34:48,710] ERROR error (org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient:540)
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://<hostname>:8983/solr/<collecname>: Not Found

**Comment by DivyaYash** [comment]
Solr server version - 6.6.2

**Comment by DivyaYash** [comment]
@jcustenborder Please advice.

**Comment by jcustenborder** [comment]
What version of solr are you using? Looks like it could be a version
mismatch.

**Comment by DivyaYash** [comment]
@jcustenborder Solr server version - 6.6.2

**Comment by jcustenborder** [comment]
If you are seeing error messages such as `Invalid version (expected 2, but 60) or the data in not in 'javabin' format` compare the version of the Solr Server against the version of solrj the connector is compiled with. This error message is most likely due to a version mismatch between the server and solrj. To address this try replacing the solr-solrj-*.jar packaged with the connector with the version that matches the Solr server you are connecting to.
